### ISSUE TITLE
🎉多谢老哥贡献

### ISSUE THREAD

**Issue by SanLeen** [xiaoMGitHub/ASUS_X450JB_Hackintosh#1]
# 🥳 多谢老哥的奉献

- 🤕 我也去专门换了BCM94352HMB，但是好像蓝牙用不了，我后面重装试下
- 🟢 建议README里面放个网盘链接以方便不了解Git的普通用户
- ❤ 期待10.15正式版

**Comment by xiaoMGitHub** [comment]
@LeenSamZiv 蓝牙驱动要装到L/E里面。应该不会有10.15了，我已经更换了笔记本，哈哈

**Comment by SanLeen** [comment]
🤣好吧，3Q
