### ISSUE TITLE
10.15.3睡眠唤醒过后会重启

### ISSUE THREAD

**Issue by abandon17** [xiaoMGitHub/ASUS_X450JB_Hackintosh#2]
不知道为什么睡眠唤醒过后总是出现重启的现象

**Comment by abandon17** [comment]
解决乐，内核补丁
Find: 63 6F 6D 2E 61 70 70 6C 65 00 5F 5F 6B 65 72 6E 65 6C 5F 5F 00
Repl: 6E 6F 74 2E 61 70 70 6C 65 00 5F 5F 6B 65 72 6E 65 6C 5F 5F 00

**Comment by wyg1997** [comment]
@abandon17 你好， 我也遇到了这个问题，可以稍微详细一点解释一下吗？
